/**
 * VeoLMS Local Provider Infrastructure Setup
 *
 * For the local provider there is no cloud infrastructure to provision.
 * This setup verifies that the local machine has the required tools
 * installed: Node.js 24+ and FFmpeg, configures storage (local or S3-compatible),
 * and generates per-app .env files.
 *
 * Dispatched via: apps/fleet-manager/src/cli.ts's "infra" command
 * Triggered by:   pnpm fleet:infra  (when FLEET_PROVIDER=local)
 */

import { execSync } from "node:child_process";
import * as fs from "node:fs/promises";
import * as fsSync from "node:fs";
import * as path from "node:path";
import { stdin as input, stdout as output } from "node:process";
import * as readline from "node:readline/promises";
import { fileURLToPath } from "node:url";
import type {
  ProviderConfigOptions,
  ProviderConfigResult,
  ProviderInfraOptions,
  ProviderInfraResult,
} from "@veolms/fleet-types";
import {
  ask,
  bold,
  cyan,
  dim,
  execCommand as checkCommand,
  fail,
  green,
  isNonInteractive as checkNonInteractive,
  isReadlineInterface,
  ok,
  red,
  warn,
  yellow,
} from "@veolms/fleet-types/terminal";
import {
  readExistingEnv,
  resolveRepoRoot as findRepoRoot,
  writeEnvFile as baseWriteEnvFile,
  promptStorageConfig,
} from "@veolms/fleet-types/env";
import { isMainModule } from "@veolms/fleet-types";

export { isReadlineInterface };

async function writeEnvFile(
  filePath: string,
  vars: Readonly<Record<string, string>>,
): Promise<void> {
  await baseWriteEnvFile(filePath, vars, {
    header:
      "# Generated by VeoLMS Local Infrastructure Setup\n# Run: pnpm fleet:infra --provider=local  to regenerate",
    mergeExisting: true,
  });
  ok(`Written ${bold(path.relative(process.cwd(), filePath))}`);
}

/**
 * Configures the environment and generates .env files for local provider.
 */
export async function configureEnv(
  options: ProviderConfigOptions & { rl?: readline.Interface } = {},
): Promise<ProviderConfigResult> {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const repoRoot = options.cwd
    ? path.resolve(options.cwd)
    : path.resolve(__dirname, "..", "..", "..", "..");
  const nonInteractive = checkNonInteractive(options);
  const shouldCloseRl =
    !isReadlineInterface(options.rl) && !nonInteractive && process.stdin.isTTY;
  const rl: readline.Interface | undefined = isReadlineInterface(options.rl)
    ? options.rl
    : shouldCloseRl
      ? readline.createInterface({ input, output })
      : undefined;

  try {
    console.log(`
${bold(cyan("╔══════════════════════════════════════════════════════╗"))}
${bold(cyan("║"))}        ${bold("VeoLMS Local Provider Setup")}                 ${bold(cyan("║"))}
${bold(cyan("║"))}     Verifies local machine tool dependencies         ${bold(cyan("║"))}
${bold(cyan("╚══════════════════════════════════════════════════════╝"))}
`);

    console.log(`\n${bold(cyan("[1/3]"))} ${bold("Checking Node.js")}`);
    console.log(dim("─".repeat(52)));

    const nodeVersion = checkCommand("node --version");
    if (!nodeVersion) {
      fail("Node.js not found.");
      console.error(`
  ${bold("Install Node.js 24:")}
    ${cyan("curl -fsSL https://deb.nodesource.com/setup_24.x | bash -")}
    ${cyan("apt-get install -y nodejs")}
`);
      throw new Error("Node.js is required but not installed.");
    }

    const major = parseInt(
      nodeVersion.replace("v", "").split(".")[0] ?? "0",
      10,
    );
    if (major < 24) {
      warn(`Node.js ${nodeVersion} found — version 24+ is required.`);
      warn(
        `Upgrade: ${cyan("https://nodejs.org")} or use ${cyan("nvm install 24")}`,
      );
    } else {
      ok(`Node.js ${bold(nodeVersion)} — OK`);
    }

    console.log(`\n${bold(cyan("[2/3]"))} ${bold("Checking FFmpeg")}`);
    console.log(dim("─".repeat(52)));

    const ffmpegVersion = checkCommand("ffmpeg -version");
    if (!ffmpegVersion) {
      fail("FFmpeg not found.");
      console.error(`
  ${bold("Install FFmpeg:")}
    ${cyan("apt-get update && apt-get install -y ffmpeg")}   ${dim("# Debian / Ubuntu")}
    ${cyan("brew install ffmpeg")}                           ${dim("# macOS")}
    ${cyan("winget install Gyan.FFmpeg")}                    ${dim("# Windows")}
`);
      throw new Error("FFmpeg is required but not installed.");
    }

    const ffmpegLine = ffmpegVersion.split(/\r?\n/)[0]?.trim() ?? "";
    ok(`FFmpeg found — ${bold(ffmpegLine.split(",")[0] ?? ffmpegLine)}`);

    console.log(
      `\n${bold(cyan("[3/3]"))} ${bold("Configuring Environment (.env)")}`,
    );
    console.log(dim("─".repeat(52)));

    const fleetEnvPath = path.join(repoRoot, "apps", "fleet-manager", ".env");
    const workerEnvPath = path.join(repoRoot, "apps", "media-worker", ".env");

    const rootEnv = await readExistingEnv(path.join(repoRoot, ".env"));
    const existingFleetEnv = await readExistingEnv(fleetEnvPath);
    const existingWorkerEnv = await readExistingEnv(workerEnvPath);

    const defaultDatabaseUrl =
      process.env.DATABASE_URL ||
      existingFleetEnv["DATABASE_URL"] ||
      existingWorkerEnv["DATABASE_URL"] ||
      rootEnv["DATABASE_URL"] ||
      "postgresql://veolms:veolms@localhost:5433/veolms";

    const databaseUrl = await ask(
      rl,
      "PostgreSQL DATABASE_URL (for worker status & job claims)",
      defaultDatabaseUrl,
      nonInteractive,
    );

    // Prompt for storage configuration (local or S3-compatible)
    const storageResult = await promptStorageConfig({
      rl,
      provider: "local",
      existingEnv: {
        ...rootEnv,
        ...existingWorkerEnv,
        ...existingFleetEnv,
        ...options.env,
      },
      nonInteractive,
    });

    const fleetEnv: Record<string, string> = {
      FLEET_PROVIDER: "local",
      PROVIDER: "local",
      FLEET_MODE: "serverful",
      MAX_WORKERS: "4",
      DATABASE_URL: databaseUrl,
      ...storageResult.envVars,
    };

    const workerEnv: Record<string, string> = {
      FLEET_PROVIDER: "local",
      DATABASE_URL: databaseUrl,
      WORKER_IDLE_POLL_SECONDS: "15",
      LOCAL_STORAGE_ROOT: "s3-bucket",
      ...storageResult.envVars,
    };

    await writeEnvFile(fleetEnvPath, fleetEnv);
    await writeEnvFile(workerEnvPath, workerEnv);

    return {
      provider: "local",
      envFiles: [fleetEnvPath, workerEnvPath],
      config: {
        storageProvider: storageResult.storageProvider,
        ...storageResult.envVars,
      },
      details: {
        storageProvider: storageResult.storageProvider,
        ...storageResult.envVars,
      },
    };
  } finally {
    if (shouldCloseRl && rl) {
      rl.close();
    }
  }
}

/**
 * Provisions local infrastructure (storage directories and verification).
 */
export async function provisionInfra(
  _options: ProviderInfraOptions = {},
): Promise<ProviderInfraResult> {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const repoRoot = path.resolve(__dirname, "..", "..", "..", "..");

  const s3BucketDir = path.join(repoRoot, "s3-bucket");
  await fs.mkdir(path.join(s3BucketDir, "raw"), { recursive: true });
  await fs.mkdir(path.join(s3BucketDir, "output"), { recursive: true });
  ok(
    `Local storage directory verified at ${bold(path.relative(process.cwd(), s3BucketDir))}`,
  );

  console.log(`
${bold(cyan("╔══════════════════════════════════════════════════════╗"))}
${bold(cyan("║"))}            ${bold(green("Local Setup Complete!"))}                ${bold(cyan("║"))}
${bold(cyan("╚══════════════════════════════════════════════════════╝"))}

${bold("Generated .env Files:")}
  ${green("✔")} apps/fleet-manager/.env
  ${green("✔")} apps/media-worker/.env

${bold("Next Steps:")}
  1. Start Fleet Manager daemon:            ${cyan("pnpm fleet:cli run daemon")}
  2. Queue & trigger a test transcoding:    ${cyan("pnpm fleet:queue:trigger")}
  3. Monitor fleet health & status:         ${cyan("pnpm fleet:cli status")}
`);

  return {
    success: true,
    provider: "local",
  };
}

/**
 * Full infrastructure setup workflow:
 * 1. Checks if update (--update) or fresh setup
 * 2. Runs configureEnv()
 * 3. Prompts user to check .env files and confirm
 * 4. Runs provisionInfra()
 */
export async function runInfraSetup(
  options: ProviderInfraOptions = {},
): Promise<void> {
  const nonInteractive = checkNonInteractive(options);
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const repoRoot = path.resolve(__dirname, "..", "..", "..", "..");
  const fleetEnvPath = path.join(repoRoot, "apps", "fleet-manager", ".env");
  const envExists = fsSync.existsSync(fleetEnvPath);

  if (options.update && envExists) {
    console.log(`
${bold(cyan("╔══════════════════════════════════════════════════════╗"))}
${bold(cyan("║"))}         ${bold("VeoLMS Local Provider Update")}               ${bold(cyan("║"))}
${bold(cyan("║"))}    Verifying local prerequisites & directories     ${bold(cyan("║"))}
${bold(cyan("╚══════════════════════════════════════════════════════╝"))}
`);
    await provisionInfra(options);
    return;
  }

  let rl: readline.Interface | undefined;
  if (!nonInteractive && process.stdin.isTTY) {
    rl = readline.createInterface({ input, output });
  }

  try {
    if (!options.skipEnvConfig) {
      const configResult = await configureEnv({ ...options, rl });

      if (rl) {
        console.log(`
${bold(cyan("--------------------------------------------------"))}
${bold(green("✔ Configuration saved!"))}
Please check envs on the paths:
${configResult.envFiles.map((f) => `  ${cyan("• " + path.relative(process.cwd(), f))}`).join("\n")}
You can change them if needed.
`);
        const answer = (
          await rl.question(
            bold(
              yellow(
                "Proceed with infrastructure provisioning? (yes/no) [yes]: ",
              ),
            ),
          )
        )
          .trim()
          .toLowerCase();

        if (answer && answer !== "yes" && answer !== "y") {
          console.log(yellow("Infrastructure provisioning cancelled by user."));
          return;
        }
      }
    }

    await provisionInfra(options);
  } finally {
    if (rl) {
      rl.close();
    }
  }
}

export const runLocalInfraSetup = runInfraSetup;
export default runInfraSetup;

if (isMainModule(import.meta.url)) {
  runInfraSetup().catch((err: unknown) => {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`\n✘ Setup failed: ${msg}\n`);
    process.exit(1);
  });
}
